import { db, productsTable } from "@workspace/db";
import { logger } from "./logger";

const DEFAULT_PRODUCTS = [
  {
    name: "TokenAnalyzer",
    category: "Crypto Intelligence",
    tagline: "Real-time crypto intelligence at your fingertips.",
    description:
      "TokenAnalyzer delivers real-time cryptocurrency analytics, on-chain data aggregation, and market intelligence. Track token movements, wallet behaviors, and DeFi protocol activity with precision. Built for traders, researchers, and protocol developers who need reliable on-chain data.",
    version: "v1.8.3",
    status: "Beta",
    features: [
      "Real-time price feeds",
      "On-chain analytics",
      "Wallet tracking & alerts",
      "DeFi protocol monitoring",
      "Custom alert system",
      "Portfolio overview",
    ],
    logoUrl: null,
    websiteUrl: null,
    apkUrl: null,
    githubUrl: "https://github.com/tokenanalyzer",
    telegramUrl: "https://t.me/dil3413",
    screenshot1Url: null,
    screenshot2Url: null,
    screenshot3Url: null,
    screenshot4Url: null,
    accentColor: "bg-indigo-600",
    sortOrder: 1,
  },
  {
    name: "GhostHub",
    category: "Developer Suite",
    tagline: "Invisible infrastructure for modern developers.",
    description:
      "GhostHub is a comprehensive developer suite that provides invisible infrastructure management, automated deployments, and seamless CI/CD integrations. Built for developers who need reliability without the overhead of managing complex infrastructure manually.",
    version: "v2.4.1",
    status: "Active",
    features: [
      "Automated CI/CD pipelines",
      "Zero-downtime deployments",
      "Infrastructure monitoring",
      "Multi-environment support",
      "Webhook integrations",
      "Team collaboration tools",
    ],
    logoUrl: null,
    websiteUrl: null,
    apkUrl: null,
    githubUrl: "https://github.com/tokenanalyzer",
    telegramUrl: "https://t.me/dil3413",
    screenshot1Url: null,
    screenshot2Url: null,
    screenshot3Url: null,
    screenshot4Url: null,
    accentColor: "bg-violet-600",
    sortOrder: 2,
  },
  {
    name: "Nexa AI",
    category: "AI Assistant",
    tagline: "Your intelligent AI companion for every task.",
    description:
      "Nexa AI is a context-aware AI assistant built for power users. Features long-term memory, multi-modal support, custom persona configuration, and deep integration with productivity workflows. Designed to work the way you think.",
    version: "v3.1.0",
    status: "Active",
    features: [
      "Long-term memory context",
      "Multi-modal inputs",
      "Custom AI personas",
      "Workflow integrations",
      "Voice interaction",
      "API access",
    ],
    logoUrl: null,
    websiteUrl: null,
    apkUrl: null,
    githubUrl: null,
    telegramUrl: "https://t.me/dil3413",
    screenshot1Url: null,
    screenshot2Url: null,
    screenshot3Url: null,
    screenshot4Url: null,
    accentColor: "bg-blue-600",
    sortOrder: 3,
  },
  {
    name: "S.A.H Ultimate 8.7",
    category: "Productivity & Automation",
    tagline: "The ultimate automation suite for peak productivity.",
    description:
      "S.A.H Ultimate is the flagship productivity and automation platform. Combines task automation, workflow orchestration, and AI-powered scheduling into a single unified workspace for individuals and teams who need to do more with less.",
    version: "v8.7.0",
    status: "Active",
    features: [
      "Workflow automation engine",
      "AI task scheduling",
      "Cross-app integrations",
      "Smart notifications",
      "Analytics dashboard",
      "Mobile companion app",
    ],
    logoUrl: null,
    websiteUrl: null,
    apkUrl: null,
    githubUrl: null,
    telegramUrl: "https://t.me/dil3413",
    screenshot1Url: null,
    screenshot2Url: null,
    screenshot3Url: null,
    screenshot4Url: null,
    accentColor: "bg-purple-600",
    sortOrder: 4,
  },
  {
    name: "Prompt Pilot",
    category: "Prompt Engineering",
    tagline: "Engineer better prompts. Get better results.",
    description:
      "Prompt Pilot is a professional prompt engineering environment. Test, iterate, version, and deploy prompts across multiple LLM providers. Built for AI engineers who treat prompts as production code and need reproducible, version-controlled prompt management.",
    version: "v2.0.0",
    status: "Active",
    features: [
      "Visual prompt builder",
      "Multi-LLM testing",
      "Version control for prompts",
      "Performance benchmarking",
      "Team prompt library",
      "One-click deployment",
    ],
    logoUrl: null,
    websiteUrl: null,
    apkUrl: null,
    githubUrl: "https://github.com/tokenanalyzer",
    telegramUrl: "https://t.me/dil3413",
    screenshot1Url: null,
    screenshot2Url: null,
    screenshot3Url: null,
    screenshot4Url: null,
    accentColor: "bg-fuchsia-600",
    sortOrder: 5,
  },
  {
    name: "Post Agent",
    category: "Content Automation",
    tagline: "Automate your content. Amplify your reach.",
    description:
      "Post Agent automates social media content creation and scheduling across platforms. Uses AI to generate platform-optimized content, manage posting schedules, and analyze engagement metrics. Your personal content team that never sleeps.",
    version: "v1.2.0",
    status: "Beta",
    features: [
      "AI content generation",
      "Multi-platform scheduling",
      "Engagement analytics",
      "Content calendar",
      "Brand voice training",
      "Hashtag optimization",
    ],
    logoUrl: null,
    websiteUrl: null,
    apkUrl: null,
    githubUrl: null,
    telegramUrl: "https://t.me/dil3413",
    screenshot1Url: null,
    screenshot2Url: null,
    screenshot3Url: null,
    screenshot4Url: null,
    accentColor: "bg-pink-600",
    sortOrder: 6,
  },
];

export async function seedProductsIfEmpty(): Promise<void> {
  try {
    const existing = await db.select().from(productsTable).limit(1);
    if (existing.length > 0) {
      return;
    }
    await db.insert(productsTable).values(DEFAULT_PRODUCTS);
    logger.info("Seeded products table with default products");
  } catch (err) {
    logger.error({ err }, "Failed to seed products");
  }
}
